CREATE DATABASE SV_HTTT09
GO

USE SV_HTTT09
GO

CREATE TABLE tbl_SinhVien
(
	MASV CHAR (10) NOT NULL,
	HOVATEN NVARCHAR (100) NOT NULL,
	NGAYSINH DATE,
	GIOITINH CHAR(3),
	MALOP CHAR (10) NOT NULL,

	PRIMARY KEY (MASV),
	FOREIGN KEY (MALOP) REFERENCES tbl_Lop (MALOP)
)
GO

CREATE TABLE tbl_Lop
(
	MALOP CHAR (10) NOT NULL,
	TENLOP NVARCHAR (100) NOT NULL,

	PRIMARY KEY (MALOP)
)

CREATE TABLE tbl_MonHoc
(
	MAMH CHAR (10) NOT NULL,
	TENMH NVARCHAR (100) NOT NULL,
	TINCHI INT NOT NULL,

	PRIMARY KEY (MAMH) 
)
GO

CREATE TABLE tbl_Diem
(
	MASV CHAR (10) NOT NULL,
	MAMH CHAR (10) NOT NULL,s
	DIEM FLOAT,


	FOREIGN KEY (MASV) REFERENCES tbl_SinhVien (MASV),
	FOREIGN KEY (MAMH) REFERENCES tbl_MonHoc (MAMH)

)